import random

# Start message

print('\nWelcome to the number guessing game. \n')

# random number generated by computer.

computer_no = random.randint(1, 100)

# Choose Mode.

def mode_selection(): #fuction to get mode selected by user.
    modes = ['easy', 'medium', 'hard']
    user_mode = input('Select your mode: Easy/Medium/Hard : ').lower()
    if user_mode not in modes:
        print('Enter mode correctly.')
        return mode_selection()
    return user_mode

setting = mode_selection()
if setting == 'easy':
    chances = 5
elif setting == 'medium':
    chances = 3
elif setting == 'hard':
    chances = 1
print(f'\nYou selected {setting} mode. You have {chances} attempts. Let\'s start guessing.')

#  Main function that matches the user number with the computer number

def match():
    global chances 
    user_no = int(input('\nGuess a number between 1 - 100 : '))
    if type(user_no) is not int or user_no < 1 or user_no > 100:
        print('\nPlease enter valid number.')
        return match()
    elif user_no != computer_no:
        if computer_no > user_no:
            print("\nIncorect. Number is greater than", user_no)
        else:
            print('\nIncorrect. Number is less than:', user_no)
        chances -= 1
        if chances != 0:
            return match()
        else:
            print('\nGame Over. Correct number was:', computer_no)
            return
    elif user_no == computer_no:
        print(f'\nCongratulations! You guessed the correct option in {chances} attempts')
        return None


match()
